---
- name: Configure | Template server.properties file
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ minecraft_base_directory }}/versions/current/server.properties"
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0640"
  tags:
    - molecule-idempotence-notest

- name: Configure | Copy eula.txt file
  ansible.builtin.copy:
    src: eula.txt
    dest: "{{ minecraft_base_directory }}/versions/current/eula.txt"
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0640"

- name: Configure | Template whitelist.json file
  ansible.builtin.template:
    src: whitelist.json.j2
    dest: "{{ minecraft_base_directory }}/versions/current/whitelist.json"
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0640"
