---
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199 and
# https://github.com/geerlingguy/ansible-role-java/issues/64
- name: Dependencies | Ensure 'man' directory exists
  ansible.builtin.file:
    path: /usr/share/man/man1
    state: directory
    mode: "0755"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 18

- name: Dependencies | Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600

- name: Dependencies | Install java
  ansible.builtin.apt:
    name: openjdk-21-jdk
    state: present
