---
- name: Download | Get manifest informations
  ansible.builtin.uri:
    url: "{{ minecraft_manifest_url }}"
    return_content: true
  register: minecraft_manifest

- name: Download | Get manifest file for {{ minecraft_version }}
  ansible.builtin.uri:
    url: "{{ minecraft_manifest.json.versions | selectattr('id','match', (minecraft_version|string) ) | map(attribute='url')  | list | first }}"
    return_content: true
  register: minecraft_manifest_version

- name: Download | Download Minecraft server
  ansible.builtin.get_url:
    url: "{{ minecraft_manifest_version.json.downloads.server.url }}"
    dest: "{{ minecraft_base_directory }}/server/{{ minecraft_version }}/server.jar"
    checksum: "sha1:{{ minecraft_manifest_version.json.downloads.server.sha1 }}"
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"
