---
- name: Structure | Create base directory
  ansible.builtin.file:
    path: "{{ minecraft_base_directory }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create jar directory
  ansible.builtin.file:
    path: "{{ minecraft_base_directory }}/jar"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create jar version directory
  ansible.builtin.file:
    path: "{{ minecraft_base_directory }}/jar/{{ minecraft_version }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create current link
  ansible.builtin.file:
    src: "{{ minecraft_base_directory }}/jar/{{ minecraft_version }}"
    dest: "{{ minecraft_base_directory }}/jar/current"
    state: link
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
