---
- name: Structure | Create base directory
  ansible.builtin.file:
    path: "{{ minecraft_base_directory }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create versions directory
  ansible.builtin.file:
    path: "{{ minecraft_versions_folder }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create current version directory
  ansible.builtin.file:
    path: "{{ minecraft_current_version_folder }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create current version link
  ansible.builtin.file:
    src: "{{ minecraft_current_version_folder }}"
    dest: "{{ minecraft_current_version_link }}"
    state: link
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"

- name: Structure | Create world directory
  ansible.builtin.file:
    path: "{{ minecraft_world_folder }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create world link
  ansible.builtin.file:
    src: "{{ minecraft_world_folder }}"
    dest: "{{ minecraft_current_version_folder }}/{{ minecraft_level_name }}"
    state: link
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"

- name: Structure | Create logs directory
  ansible.builtin.file:
    path: "{{ minecraft_logs_folder }}"
    state: directory
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
    mode: "0750"

- name: Structure | Create logs link
  ansible.builtin.file:
    src: "{{ minecraft_logs_folder }}"
    dest: "{{ minecraft_current_version_folder }}/logs"
    state: link
    owner: "{{ minecraft_user_name }}"
    group: "{{ minecraft_user_name }}"
