---
- name: User | Create group {{ minecraft_user_name }}
  ansible.builtin.group:
    name: "{{ minecraft_user_name }}"
    state: present

- name: User | Create user {{ minecraft_user_name }}
  ansible.builtin.user:
    name: "{{ minecraft_user_name }}"
    state: present
